logging:
  config: classpath:log4j2.properties
  level:
    com.gin: debug

spring:
  datasource:
    url: jdbc:mysql://47.102.208.73:3306/${databse.name}?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    #    url: jdbc:mysql://localhost:3306/${databse.name}?serverTimezone=GMT%2B8&characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: dzkjd719
#    password: lzbx2837200
